spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAVT7FZ27L7BM557J6
  secretKey: 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
  bucketName: hui5.wang.dhc.com.cn

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies
